version: "3.9"

services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: factory_api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    restart: always

  ai-worker:
    build:
      context: ..
      dockerfile: docker/gpu.Dockerfile
    container_name: factory_ai
    env_file:
      - ../.env
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  db:
    image: postgres:15
    container_name: factory_db
    environment:
      POSTGRES_DB: factory_ai
      POSTGRES_USER: factory
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
